CREATE TABLE IF NOT EXISTS CLIENT (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(1000) NOT NULL CHECK(LENGTH(NAME) >= 3 AND LENGTH(NAME) <= 200)
);

CREATE TABLE IF NOT EXISTS PLANET (
ID VARCHAR PRIMARY KEY NOT NULL CHECK (ID REGEXP '^[A-Z0-9]+$'),
NAME VARCHAR(500) NOT NULL CHECK(LENGTH(NAME) >= 1 AND LENGTH(NAME) <= 500)
);

CREATE TABLE IF NOT EXISTS TICKET (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
CREATED_AT TIMESTAMP NOT NULL,
CLIENT_ID BIGINT REFERENCES CLIENT(ID),
FROM_PLANET_ID VARCHAR REFERENCES PLANET(ID),
TO_PLANET_ID VARCHAR REFERENCES PLANET(ID)
);